title: "IF Music School"
description: "Learn music the modern way – with YouTube, Udemy, and more"
baseurl: "" 
url: "https://obmij.github.io/ifmusic/"
theme: jekyll-theme-cayman


header_pages:
  - about.md
  - youtube.md
  - udemy.md
  - contact.md
